---
title: "Predictive-analytics-on-Cancer-statictics-at-county-level"
author: "Chintan Nayak"
date: "30/03/2022"
output: html_document
---


```{r}
require(tidyverse, quietly= TRUE)
library( tidyverse)
library(tidymodels)
library(dplyr)
```


## Using left Join to merge the two datasets

```{r}
incidents = read.csv("/Users/HP/Documents/incd.csv")
death= read.csv("/Users/HP/Documents/death.csv")
```

```{r}
merged= incidents%>%
  left_join(death, by="FIPS")
```

```{r}
merged
```

```{r}
set.seed(999)
data_split=initial_split(merged, prop=.75)
testing_data=testing(data_split)
training_data=training(data_split)
```


## Linear regression

```{r}
main_recipe =recipe(Age_Adjusted_Incident_Rate~ Incident_Recent_5.Year_Trend + Average_Annual_Incident_Count + Age_Adjusted_Death_Rate + Death_Recent_5.Year_Trend + FIPS, training_data)%>%
  step_dummy(all_nominal())%>%
  step_nzv(all_predictors())

reg_model= linear_reg()%>%
  set_engine('lm')

reg_flow= workflow()%>%
  add_model(reg_model)%>%
  add_recipe(main_recipe)

reg_fit= reg_flow%>%
  fit(training_data)
tidy(reg_fit)
```


```{r}
reg_results=predict(reg_fit, testing_data)%>%
  bind_cols(testing_data%>%select(Age_Adjusted_Incident_Rate))
```


```{r}
multi_metric<-metric_set(rsq, rmse,mae, mape)

multi_metric(reg_results, truth= Age_Adjusted_Incident_Rate , estimate=.pred)%>%
  mutate(across(where(is.numeric), ~round(.x,2)))
```


#5-fold cross validation

```{r}
set.seed(999)
folds_train= vfold_cv(training_data, v=5)

fit_train= reg_flow%>%
              fit_resamples(folds_train)

collect_metrics(fit_train)%>%
   mutate(across(where(is.numeric), ~round(.x,2)))
```


```{r}
set.seed(999)
folds_test= vfold_cv(testing_data, v=5)

fit_test= reg_flow%>%
              fit_resamples(folds_test)

collect_metrics(fit_test)%>%
   mutate(across(where(is.numeric), ~round(.x,2)))
```


#Now I am trying to improve the original model with Generalized Additive Models method.

```{r}
additive_model= gen_additive_mod(mode='regression',
                                 select_features=TRUE,
                                 adjust_deg_free=10)%>%
  set_engine('mgcv')

a_model= additive_model%>% fit(Age_Adjusted_Incident_Rate~ s(Incident_Recent_5.Year_Trend)+
                                s(Average_Annual_Incident_Count)+
                                s(Age_Adjusted_Death_Rate)+
                                s(Death_Recent_5.Year_Trend)+
                                s(FIPS), data=training_data)


results_a=predict(a_model, testing_data)%>%
  bind_cols(testing_data%>%select(Age_Adjusted_Incident_Rate))

multi_metric(results_a, truth=Age_Adjusted_Incident_Rate, estimate=.pred)%>%
   mutate(across(where(is.numeric), ~round(.x, 2)))

```

